### ISSUE TITLE
Fix like? method for Logical Interconnect Groups

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-sdk-ruby#89]
Default `like?` method is not working properly for Logical Interconnect Groups with Interconnects attached and Uplinks Sets defined.
- oneview-ruby-sdk version:  2.x

**Comment by ricardogpsf** [comment]
Do you remember how reproduce this problem?
How did you do the comparison?

**Comment by ricardogpsf** [comment]
I talked with @tmiotto and he explained to me about this problem, that occurs because when we create a new Logical Interconnect Group (LIG) the interconnect and uplinkset are passed using one specific format (a specific hash of data) and when this data come from server, the hash of data has the another format, generating a wrong comparison using the `like?` method.
